### ISSUE TITLE
Building for specific blender versions

### ISSUE THREAD

**Issue by TheDuckCow** [StandingPadAnimations/bpy-build#1]
In my case, I have many versions of Blender on my system and I definitely don't want to install every time to each of them.

As you know, I am a fan of having a config file for which lets the developer decide which versions they *want* to install it (something akin to a requirements.txt if you will). Right now MCprep is using this build system and is being installed to even 2.7x versions still on my machine, which means a lot of complaining on startup. Not that this is a major problem for me, basically never using 2.7x again now, but there are other scenarios where it may be helpful.

Likewise, it could also be nice to have flags to install to a specific blender versions as well, something like: `bpy-addon-build -b dev -v 3.6`.

For the "versions to install to" config, it could be a text file containing just blender versions without their paths. Nice thing is, this could even serve as documentation (in a way) as to the canonically supported blender versions of a given addon. I think `blender_installs.txt` is a reasonable name to keep, but open to whatever.

I almost wonder if the tool should *require* specifying either a version (`-v 3.6`, a file (`-v blender_installs.txt`), or an all flag (`-v all`) and if not, enter a sort of interactive mode so it's clear what's about to happen.

**Comment by TheDuckCow** [comment]
Ok I will admit, I totally missed that the config info *is* actually in the yaml, so that part is great. I still think it could be nice to have a flag to install only a specific version though, and just make it so the default is `-all` which would basically seek those in the yaml file. But less pressing imo.

**Comment by StandingPadAnimations** [comment]
This has been added in 70395a0
