### ISSUE TITLE
Option to silence certain lint warnings

### ISSUE THREAD

**Issue by TheDuckCow** [StandingPadAnimations/bpy-build#2]
Auto lint feature is great - though with a million and one `W191` errors, it makes it basically noisy and useless for a repo that has tabs as a convention. Would be great to have a config somehow, like most linters do, to specify what to ignore. Even better if that can be part of the yaml file, since we'd expect all developers for a repo should be following the same linting standards.

**Comment by TheDuckCow** [comment]
I should add, it seems like it actually *is* attempting to ignore a rule actually. See my console output:

```
(venv) mcprep $ bpy-addon-build -b dev
['flake8 --extend-ignore W191 .']
...
./__init__.py:37:80: E501 line too long (80 > 79 characters)
./__init__.py:38:80: E501 line too long (90 > 79 characters)
./__init__.py:42:1: W191 indentation contains tabs
./__init__.py:43:1: W191 indentation contains tabs
./__init__.py:44:1: W191 indentation contains tabs
```

Is it picking this up from my local config perhaps..? Though my other comment stands around wanting to have consistent linting for all developers as much as possible.

**Comment by StandingPadAnimations** [comment]
Linting is not a `bpy-addon-build` feature, it's part of the build config for the addon. For MCprep, it's in the default build option
